import { ShoeItem, SaleOrder } from '../types';

export const INITIAL_SHOES: ShoeItem[] = [
  {
    id: 'SCR-1001',
    sku: 'SCR-1001',
    title: 'Nike Air Max 90 OG Infrared',
    brand: 'Nike',
    category: 'Sneakers',
    size: 'EU 42 / US 8.5',
    sizeEU: 42,
    conditionGrade: '9/10 Excellent Preloved',
    color: 'White / Black / Neutral Grey / Radiant Red',
    costPrice: 3200,
    sellingPrice: 7800,
    status: 'sold',
    image: '/images/nike-sneaker.jpg',
    notes: 'Imported thrift bale grade A. Minimal outsole wear, clean insoles.',
    dateAdded: '2025-02-10',
    dateSold: '2025-02-14',
    saleId: 'ORD-2025-101',
  },
  {
    id: 'SCR-1002',
    sku: 'SCR-1002',
    title: 'Adidas UltraBoost 21 Triple Black',
    brand: 'Adidas',
    category: 'Running / Athletic',
    size: 'EU 43.5 / US 9.5',
    sizeEU: 43.5,
    conditionGrade: '9.5/10 Like New (Tried On)',
    color: 'Core Black / Core Black',
    costPrice: 4500,
    sellingPrice: 9500,
    status: 'sold',
    image: '/images/adidas-sneaker.jpg',
    notes: 'Near mint condition. Continental rubber tread 98% remaining.',
    dateAdded: '2025-02-12',
    dateSold: '2025-02-18',
    saleId: 'ORD-2025-102',
  },
  {
    id: 'SCR-1003',
    sku: 'SCR-1003',
    title: 'New Balance 2002R Protection Pack Rain Cloud',
    brand: 'New Balance',
    category: 'Retro & Vintage',
    size: 'EU 42.5 / US 9',
    sizeEU: 42.5,
    conditionGrade: '9/10 Excellent Preloved',
    color: 'Rain Cloud / Magnet',
    costPrice: 5200,
    sellingPrice: 11800,
    status: 'sold',
    image: '/images/nb-sneaker.jpg',
    notes: 'Highly demanded model. Suede brushed and disinfected.',
    dateAdded: '2025-02-15',
    dateSold: '2025-02-20',
    saleId: 'ORD-2025-103',
  },
  {
    id: 'SCR-1004',
    sku: 'SCR-1004',
    title: 'Dr. Martens 1460 Smooth Leather 8-Eye Boots',
    brand: 'Dr. Martens',
    category: 'Boots & Leather',
    size: 'EU 41 / UK 7',
    sizeEU: 41,
    conditionGrade: '8.5/10 Very Good Thrift',
    color: 'Cherry Red Smooth',
    costPrice: 4800,
    sellingPrice: 10500,
    status: 'available',
    image: '/images/leather-boots.jpg',
    notes: 'Authentic yellow welt stitching. Minor leather creases, vintage appeal.',
    dateAdded: '2025-02-18',
  },
  {
    id: 'SCR-1005',
    sku: 'SCR-1005',
    title: 'Air Jordan 1 Retro High OG Chicago',
    brand: 'Jordan',
    category: 'Retro & Vintage',
    size: 'EU 44 / US 10',
    sizeEU: 44,
    conditionGrade: '9/10 Excellent Preloved',
    color: 'Varsity Red / Black / White',
    costPrice: 6500,
    sellingPrice: 14500,
    status: 'sold',
    image: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=800&q=80',
    notes: 'Thrift find grade A+. Stars on toe box still visible.',
    dateAdded: '2025-02-19',
    dateSold: '2025-02-22',
    saleId: 'ORD-2025-104',
  },
  {
    id: 'SCR-1006',
    sku: 'SCR-1006',
    title: 'Asics Gel-Kayano 14 Metallic Plum',
    brand: 'Asics',
    category: 'Running / Athletic',
    size: 'EU 41.5 / US 8',
    sizeEU: 41.5,
    conditionGrade: '9.5/10 Like New (Tried On)',
    color: 'Cream / Plum Pure Metallic',
    costPrice: 3800,
    sellingPrice: 8900,
    status: 'available',
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
    notes: 'Y2K aesthetic mesh runner. Extremely clean interior.',
    dateAdded: '2025-02-21',
  },
  {
    id: 'SCR-1007',
    sku: 'SCR-1007',
    title: 'Converse Chuck Taylor 70 Vintage High Top',
    brand: 'Converse',
    category: 'Casual / Canvas',
    size: 'EU 42 / US 8.5',
    sizeEU: 42,
    conditionGrade: '8.5/10 Very Good Thrift',
    color: 'Parchment / Egret',
    costPrice: 1800,
    sellingPrice: 4200,
    status: 'available',
    image: 'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=800&q=80',
    notes: 'Heavyweight vintage canvas. Black heel license plate emblem.',
    dateAdded: '2025-02-22',
  },
  {
    id: 'SCR-1008',
    sku: 'SCR-1008',
    title: 'Puma Suede Classic XXI Forest Green',
    brand: 'Puma',
    category: 'Casual / Canvas',
    size: 'EU 43 / US 9.5',
    sizeEU: 43,
    conditionGrade: '8/10 Clean Used',
    color: 'Ponderosa Pine / White',
    costPrice: 2000,
    sellingPrice: 4800,
    status: 'sold',
    image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
    notes: 'Suede treated with water repellent spray before listing.',
    dateAdded: '2025-02-23',
    dateSold: '2025-02-25',
    saleId: 'ORD-2025-105',
  },
  {
    id: 'SCR-1009',
    sku: 'SCR-1009',
    title: 'Vans Old Skool Pro Skate Black/White',
    brand: 'Vans',
    category: 'Casual / Canvas',
    size: 'EU 40.5 / US 8',
    sizeEU: 40.5,
    conditionGrade: '8.5/10 Very Good Thrift',
    color: 'Black / True White',
    costPrice: 1900,
    sellingPrice: 4500,
    status: 'available',
    image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=800&q=80',
    notes: 'PopCush insole edition. Reinforced Duracap rubber upper.',
    dateAdded: '2025-02-24',
  },
  {
    id: 'SCR-1010',
    sku: 'SCR-1010',
    title: 'Timberland 6-Inch Premium Waterproof Boot',
    brand: 'Timberland',
    category: 'Boots & Leather',
    size: 'EU 44 / US 10',
    sizeEU: 44,
    conditionGrade: '9/10 Excellent Preloved',
    color: 'Wheat Nubuck',
    costPrice: 5800,
    sellingPrice: 12900,
    status: 'available',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    notes: 'Heavy duty waterproof leather. Brass eyelets, pristine collar padding.',
    dateAdded: '2025-02-25',
  },
  {
    id: 'SCR-1011',
    sku: 'SCR-1011',
    title: 'Reebok Club C 85 Vintage Chalk',
    brand: 'Reebok',
    category: 'Casual / Canvas',
    size: 'EU 41 / US 8.5',
    sizeEU: 41,
    conditionGrade: '9/10 Excellent Preloved',
    color: 'Chalk / Glen Green',
    costPrice: 2400,
    sellingPrice: 5600,
    status: 'available',
    image: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=80',
    notes: 'Soft garment leather upper. Classic 80s court styling.',
    dateAdded: '2025-02-26',
  },
  {
    id: 'SCR-1012',
    sku: 'SCR-1012',
    title: 'Hoka One One Clifton 8 Road Running',
    brand: 'Hoka',
    category: 'Running / Athletic',
    size: 'EU 45 / US 11',
    sizeEU: 45,
    conditionGrade: '9.5/10 Like New (Tried On)',
    color: 'Outer Space / Blue Glass',
    costPrice: 4800,
    sellingPrice: 10800,
    status: 'available',
    image: 'https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?auto=format&fit=crop&w=800&q=80',
    notes: 'Ultra lightweight maximalist cushion. Ideal for long distance.',
    dateAdded: '2025-02-27',
  }
];

export const INITIAL_SALES: SaleOrder[] = [
  {
    id: 'ORD-2025-101',
    shoeId: 'SCR-1001',
    shoeSKU: 'SCR-1001',
    shoeTitle: 'Nike Air Max 90 OG Infrared',
    shoeBrand: 'Nike',
    shoeSize: 'EU 42 / US 8.5',
    customerName: 'Hamza Chaudhry',
    customerPhone: '0300-8472910',
    address: 'House 142, Street 8, Phase 5 DHA',
    city: 'Lahore',
    courierName: 'TCS',
    trackingNumber: 'TCS-892014729',
    costPrice: 3200,
    agreedPrice: 7800,
    shippingFee: 250,
    totalAmount: 8050,
    paymentMethod: 'COD',
    paymentStatus: 'Paid',
    orderStatus: 'Delivered',
    orderDate: '2025-02-14',
    notes: 'Customer asked for double bubble wrap packing.',
  },
  {
    id: 'ORD-2025-102',
    shoeId: 'SCR-1002',
    shoeSKU: 'SCR-1002',
    shoeTitle: 'Adidas UltraBoost 21 Triple Black',
    shoeBrand: 'Adidas',
    shoeSize: 'EU 43.5 / US 9.5',
    customerName: 'Zubair Tariq',
    customerPhone: '0321-9823411',
    address: 'Flat 402, Al-Aziz Heights, North Nazimabad Block H',
    city: 'Karachi',
    courierName: 'PostEx',
    trackingNumber: 'PEX-77820194',
    costPrice: 4500,
    agreedPrice: 9500,
    shippingFee: 300,
    totalAmount: 9800,
    paymentMethod: 'COD',
    paymentStatus: 'Paid',
    orderStatus: 'Delivered',
    orderDate: '2025-02-18',
    notes: 'Repeat buyer from Instagram page.',
  },
  {
    id: 'ORD-2025-103',
    shoeId: 'SCR-1003',
    shoeSKU: 'SCR-1003',
    shoeTitle: 'New Balance 2002R Protection Pack Rain Cloud',
    shoeBrand: 'New Balance',
    shoeSize: 'EU 42.5 / US 9',
    customerName: 'Muhammad Arslan',
    customerPhone: '0333-5128904',
    address: 'House 89-B, Sector F-11/2',
    city: 'Islamabad',
    courierName: 'Leopard Courier',
    trackingNumber: 'LEO-44910283',
    costPrice: 5200,
    agreedPrice: 11800,
    shippingFee: 250,
    totalAmount: 12050,
    paymentMethod: 'Bank Transfer',
    paymentStatus: 'Paid',
    orderStatus: 'Delivered',
    orderDate: '2025-02-20',
    notes: 'Meezan Bank online transfer confirmed.',
  },
  {
    id: 'ORD-2025-104',
    shoeId: 'SCR-1005',
    shoeSKU: 'SCR-1005',
    shoeTitle: 'Air Jordan 1 Retro High OG Chicago',
    shoeBrand: 'Jordan',
    shoeSize: 'EU 44 / US 10',
    customerName: 'Shahzaib Hassan',
    customerPhone: '0301-4432198',
    address: 'Shop 12, Liberty Plaza, Gulberg III',
    city: 'Lahore',
    courierName: 'Trax Logistics',
    trackingNumber: 'TRAX-99820145',
    costPrice: 6500,
    agreedPrice: 14500,
    shippingFee: 0,
    totalAmount: 14500,
    paymentMethod: 'EasyPaisa',
    paymentStatus: 'Paid',
    orderStatus: 'Delivered',
    orderDate: '2025-02-22',
    notes: 'Free shipping offered as promotional discount.',
  },
  {
    id: 'ORD-2025-105',
    shoeId: 'SCR-1008',
    shoeSKU: 'SCR-1008',
    shoeTitle: 'Puma Suede Classic XXI Forest Green',
    shoeBrand: 'Puma',
    shoeSize: 'EU 43 / US 9.5',
    customerName: 'Usman Ali',
    customerPhone: '0315-7762049',
    address: 'House 12, Street 3, Saddar Cantt',
    city: 'Rawalpindi',
    courierName: 'TCS',
    trackingNumber: 'TCS-667109283',
    costPrice: 2000,
    agreedPrice: 4800,
    shippingFee: 250,
    totalAmount: 5050,
    paymentMethod: 'COD',
    paymentStatus: 'Pending',
    orderStatus: 'In Transit',
    orderDate: '2025-02-25',
    notes: 'Dispatched via TCS Express.',
  }
];

export const PAKISTAN_CITIES = [
  'Karachi',
  'Lahore',
  'Islamabad',
  'Rawalpindi',
  'Faisalabad',
  'Multan',
  'Peshawar',
  'Quetta',
  'Sialkot',
  'Gujranwala',
  'Hyderabad',
  'Abbottabad',
  'Bahawalpur',
  'Sargodha',
  'Sukkur',
  'Larkana',
  'Sheikhupura',
  'Jhelum',
  'Mardan',
  'Gujrat',
  'Wah Cantt',
  'Kasur',
  'Rahim Yar Khan',
  'Sahiwal',
  'Okara',
  'Mingora (Swat)',
  'Dera Ghazi Khan',
  'Mirpur Khas',
  'Chiniot',
  'Kamoke',
  'Attock',
  'Muzaffarabad (AJK)',
];

export const COURIER_PROVIDERS = [
  { name: 'TCS', trackingUrl: 'https://www.tcsexpress.com/tracking?track=' },
  { name: 'Leopard Courier', trackingUrl: 'https://www.leopardscourier.com/tracking/' },
  { name: 'PostEx', trackingUrl: 'https://postex.pk/tracking?id=' },
  { name: 'Trax Logistics', trackingUrl: 'https://trax.pk/tracking/' },
  { name: 'M&P', trackingUrl: 'https://mulphilog.com/tracking/' },
  { name: 'Call Courier', trackingUrl: 'https://callcourier.com.pk/tracking/' },
  { name: 'Rider Courier', trackingUrl: 'https://www.withrider.com/track/' },
  { name: 'Pakistan Post', trackingUrl: 'http://ep.gov.pk/' },
  { name: 'Self Pickup / Hand Delivery', trackingUrl: '' },
];
